### ISSUE TITLE
Some translation strings are missing

### ISSUE THREAD

**Issue by RedWavve** [pmspr4100/MA-XML-11-FRENCH#1]
Hello,
Although it's shown as "complete" on the forum, the french translation is missing pieces and bits in the latest 9.10.10 beta for the Mi 9.

Settings for now :
- Settings / Privacy
- Settings / Developers Settings
- Settings / Some permissions titles
- Settings / Lock screen

Thanks ;-)

**Comment by pmspr4100** [comment]
Bonjour
Tu peut écrire en Français.
Sinon pourrais-tu me fournir une capture d'écran STP.

**Comment by RedWavve** [comment]
Voilà les liens vers les sections qui manquent de certaines traduction. Je n'ai malheureusement pas réussi à les coller directement dans GITHUB.

https://ibb.co/94j1Pk5
https://ibb.co/df6LMSg
https://ibb.co/BN9hkjc
https://ibb.co/RYfPchF
https://ibb.co/vv7j7WX

<a href="https://ibb.co/94j1Pk5"><img src="https://i.ibb.co/94j1Pk5/Screenshot-2019-10-16-17-49-36-943-com-android-settings.jpg" alt="Screenshot-2019-10-16-17-49-36-943-com-android-settings" border="0"></a> <a href="https://ibb.co/df6LMSg"><img src="https://i.ibb.co/df6LMSg/Screenshot-2019-10-16-17-49-52-374-com-android-settings.jpg" alt="Screenshot-2019-10-16-17-49-52-374-com-android-settings" border="0"></a> <a href="https://ibb.co/BN9hkjc"><img src="https://i.ibb.co/BN9hkjc/Screenshot-2019-10-16-17-50-14-709-com-miui-home.jpg" alt="Screenshot-2019-10-16-17-50-14-709-com-miui-home" border="0"></a> <a href="https://ibb.co/RYfPchF"><img src="https://i.ibb.co/RYfPchF/Screenshot-2019-10-16-17-50-58-071-com-android-settings.png" alt="Screenshot-2019-10-16-17-50-58-071-com-android-settings" border="0"></a> <a href="https://ibb.co/vv7j7WX"><img src="https://i.ibb.co/vv7j7WX/Screenshot-2019-10-16-17-52-19-054-com-android-settings.jpg" alt="Screenshot-2019-10-16-17-52-19-054-com-android-settings" border="0"></a>

**Comment by pmspr4100** [comment]
Ok voila c'est corriger.
