### ISSUE TITLE
Suuprimer?

### ISSUE THREAD

**Issue by julien-noblet** [pmspr4100/MA-XML-11-FRENCH#11]
- **Version MIUI:** 20.1.16
- **Nom de l'appareil:** Mi 9T Pro

**Capture d'écran/Description:**
![IMG_20200119_163946](https://user-images.githubusercontent.com/9715094/72685399-ff1b6d80-3ae9-11ea-8a56-98d7b9959619.jpg)
Petite erreur de frappe

**Comment by pmspr4100** [comment]
-Corriger
