### ISSUE TITLE
Manque la fin du mot

### ISSUE THREAD

**Issue by julien-noblet** [pmspr4100/MA-XML-11-FRENCH#12]
- **Version MIUI:** 11.2 20.1.16
- **Nom de l'appareil:** Mi 9T Pro

**Capture d'écran/Description:**
![IMG_20200119_183927](https://user-images.githubusercontent.com/9715094/72685508-30486d80-3aeb-11ea-9faa-b7348dba5c10.jpg)
Lors de la capture d'écran, le mot sauvegarder n'est pas complet

**Comment by pmspr4100** [comment]
-Traduction OK 
C'est du à la taille de la police d'écriture 
![Screenshot_2020-01-19-21-21-48-967_com miui gallery](https://user-images.githubusercontent.com/49132275/72687816-0a7a9300-3b02-11ea-8c05-6721d03eb4eb.jpg)

**Comment by jblum66** [comment]
On pourrait mettre "Enreg." comme libellé pour que ça fonctionne avec la taille par défaut.

**Comment by pmspr4100** [comment]
OK normalement c'est corrigé.
À voir sur la prochaine mise à jour.
