### ISSUE TITLE
Report issue about 2 bad writing

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#14]
hello,
i report a 2 issue about bad writing found in : 
1-Paramètres - Mot de passe et sécurité - Mot de passe - mot de passe oublie
we found here bad writing like <data> and color=#e6e6e6>
2-Camera app - Paramètre - Qualité de la photo 
in here we found a word of english "fine" we say "élevée" & " très élevée"
And thank for your work .

**Comment by pmspr4100** [comment]
Merci du retour 
Merci de mettre des captures d'écran.
Pour le 2ème point corriger.
Pour le 1er j'attend des captures d'écran.

**Comment by bigjackwww** [comment]
Merci pour votre réponse ,
voilà la capture d’écran et le chemin et :  Paramètres - Mot de passe et sécurité - Mot de passe - mot de passe oublié.

![Sans titre](https://user-images.githubusercontent.com/60173587/72963266-0f1ba180-3db7-11ea-9f4e-e86b66e027ac.jpg)

**Comment by pmspr4100** [comment]
-Correction faite.
Merci
