### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#16]
- Version MIUI: 20.1.16 (Beta) 
- Nom de l'appareil: Mi CC9

Salut , j'ai trouver un bugs dans le chemin : Paramétrés - Paramétrés Additionnels - Accessibilité 

Capture d’écran : 

![Screenshot_2020-02-14-02-25-15-483_com android settings](https://user-images.githubusercontent.com/60173587/74493845-71a62000-4ed3-11ea-91b2-56572342cfc0.jpg)
![Screenshot_2020-02-14-02-25-21-031_com android settings](https://user-images.githubusercontent.com/60173587/74493858-7a96f180-4ed3-11ea-9553-2f434726e0a8.jpg)

**Comment by pmspr4100** [comment]
Une partie et corriger.

**Comment by bigjackwww** [comment]
Merci beaucoup.

**Comment by pmspr4100** [comment]
-Fixer
