### ISSUE TITLE
Quelque Bugs

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#17]
- Version MIUI: 20.1.16 (Beta)
- Nom de l'appareil:** Mi CC9

Salut , j'ai trouver quelque bugs dans le chemin : 
- Paramètres - Affichage permanent et écran de verrouillage - Fond d'écran carrousel 
- Capture d'écran :
![1](https://user-images.githubusercontent.com/60173587/74711019-439e4400-5223-11ea-831d-3921acd23871.jpg)

Et dans le chemin : 
- Paramètres - Affichage permanent et écran de verrouillage - Fond d'écran carrousel - Paramètres de Diaporama
- Capture d'écran :
![2](https://user-images.githubusercontent.com/60173587/74711251-d3dc8900-5223-11ea-806c-42cfb9c9ff9d.jpg)
![3](https://user-images.githubusercontent.com/60173587/74711261-d939d380-5223-11ea-9c73-4ab7da4dd51c.jpg)

Et dans le chemin : 
Paramètres - Affichage permanent et écran de verrouillage - Fond d'écran carrousel - A propos
- Capture d'écran :
![4](https://user-images.githubusercontent.com/60173587/74711396-32096c00-5224-11ea-8270-f44420eb680c.jpg)
![5](https://user-images.githubusercontent.com/60173587/74711415-3897e380-5224-11ea-894f-07fb35c70bd9.jpg)

Et dans le chemin : 
Paramètres - Affichage permanent et écran de verrouillage - Afficher les fichiers
- Capture d'écran :
![6](https://user-images.githubusercontent.com/60173587/74712399-7dbd1500-5226-11ea-9c93-a436fd5f1492.jpg)

Et dans le chemin : 
Paramètres - Retour D'informations
- Capture d'écran :
![7](https://user-images.githubusercontent.com/60173587/74722661-9682f600-5239-11ea-976c-f0fd2cc13232.jpg)

**Comment by pmspr4100** [comment]
-Fixer en partie.

**Comment by bigjackwww** [comment]
Merci.

**Comment by pmspr4100** [comment]
-Fixer
