### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#18]
- Version MIUI: 20.1.16 (Beta)
- Nom de l'appareil:** Mi CC9
Salut , j'ai trouver un bug dans le chemin :

Paramètres - Paramètre additionnels -  Date et heure
- Capture d'écran :
![8](https://user-images.githubusercontent.com/60173587/74805445-642dd300-52e3-11ea-92ec-3d9c90547fa8.jpg)

**Comment by pmspr4100** [comment]
-Corriger

**Comment by bigjackwww** [comment]
Merci .
