### ISSUE TITLE
Quelque issues

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#24]
- **Version MIUI:  20.2.27 (beta)
- **Nom de l'appareil:  Mi CC9

Salut , j'ai trouver quelque bugs dans le chemin :

- **Paramètres - Mon appareil - Informations Légales

- **Capture d'écran :

![1](https://user-images.githubusercontent.com/60173587/75513278-b7dfa100-59f4-11ea-970a-5a7afcbc7693.jpg)
![2](https://user-images.githubusercontent.com/60173587/75513281-bb732800-59f4-11ea-84bf-e3084a31b4b2.jpg)

- **Paramètres -  Connexion et partage  -  Caster  -  Démos

 - **Capture d'écran :

![3](https://user-images.githubusercontent.com/60173587/75513492-51a74e00-59f5-11ea-96b1-7c9485aaabcb.jpg)

- **Paramètres -  Connexion et partage  -  Caster  -  Aide

 - **Capture d'écran :

![4](https://user-images.githubusercontent.com/60173587/75513564-84514680-59f5-11ea-97d2-7387de2ef1b4.jpg)

- **Paramètres - Affichage permanent et écran de verrouillage  -  Fond d'écran carrousel -  Salutations du matin 

  - **Capture d'écran :

![5](https://user-images.githubusercontent.com/60173587/75513716-f164dc00-59f5-11ea-93ef-95b87002c6b2.jpg)

- **Paramètres - Paramètres Bluetooth - Paramètre additionnels  

- **Capture d'écran :

![6](https://user-images.githubusercontent.com/60173587/75513958-9b446880-59f6-11ea-9fc5-462958a44564.jpg)

- **Paramètres -   Affichage  -  Niveau de luminosité

 - **Capture d'écran :

![7](https://user-images.githubusercontent.com/60173587/75514294-713f7600-59f7-11ea-8a4a-0fbd6ff0ad92.jpg)

- **Paramètres -   Affichage  - Mode Lecture

 - **Capture d'écran :

![8](https://user-images.githubusercontent.com/60173587/75514330-8c11ea80-59f7-11ea-855a-6ba878262eac.jpg)

- **Paramètres - Ecran d’accueil

 - **Capture d'écran :

![9](https://user-images.githubusercontent.com/60173587/75514625-2ffb9600-59f8-11ea-8693-0a5af2038064.jpg)

- **Paramètres - Mot de Passe et Sécurité  - Alertes D'urgence 

 - **Capture d'écran :

![10](https://user-images.githubusercontent.com/60173587/75514846-c6c85280-59f8-11ea-9221-adebaff92c28.jpg)

- **Paramètres -   Bien être numérique

- **Capture d'écran :

![11](https://user-images.githubusercontent.com/60173587/75515115-7a314700-59f9-11ea-9c5a-72a80d537a8f.jpg)
![12](https://user-images.githubusercontent.com/60173587/75515117-7d2c3780-59f9-11ea-86b9-417fc73a322c.jpg)

- **Paramètres - Paramètre additionnels  -  Options pour les développeurs 

- **Capture d'écran :

![13](https://user-images.githubusercontent.com/60173587/75515548-9da8c180-59fa-11ea-99ac-a4f6f6d38cbe.jpg)

- **Paramètres -  Connexion et partage  -  Point d’accès  - Appareils connectés 

- **Capture d'écran :

![14](https://user-images.githubusercontent.com/60173587/75516032-be254b80-59fb-11ea-8737-aaba82acf01a.jpg)

 

- **Paramètres - Paramètre additionnels  -  Options pour les développeurs   -  Mode Sombre

- **Capture d'écran : 

![Screenshot_2020-02-28-07-36-32-568_com android settings](https://user-images.githubusercontent.com/60173587/75517701-9afc9b00-59ff-11ea-879d-5d6d6a67c693.jpg)

 

- **Paramètres - Paramètre additionnels  -  Options pour les développeurs  -  Traçage système 

- **Capture d'écran :

![Screenshot_2020-02-28-07-37-44-217_com android traceur](https://user-images.githubusercontent.com/60173587/75517513-2fb2c900-59ff-11ea-8991-0532ad88c583.jpg)

- **Paramètres - Paramètre additionnels  -  Options pour les développeurs  
 

- **Capture d'écran :
![Screenshot_2020-02-28-07-41-54-456_com android settings](https://user-images.githubusercontent.com/60173587/75517565-478a4d00-59ff-11ea-9073-d1f0bdf7c4a2.jpg)

**Comment by pmspr4100** [comment]
-Fixé

**Comment by bigjackwww** [comment]
Merci beaucoup
