### ISSUE TITLE
Mi Calculator

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#25]
- Version MIUI:   20.2.27 (beta)
- Nom de l'appareil:   Mi CC9

Salut , j'ai trouver quelque bugs dans l'application Mi Calculator : 

- Capture d'écran :
![Screenshot_2020-03-01-07-55-00-689_com miui calculator](https://user-images.githubusercontent.com/60173587/75621388-f495ce80-5b93-11ea-82a4-3899529f7ff0.jpg)
![Screenshot_2020-03-01-07-55-07-850_com miui calculator](https://user-images.githubusercontent.com/60173587/75621389-f8c1ec00-5b93-11ea-82d5-4e752b9cf723.jpg)
![Screenshot_2020-03-01-07-55-17-730_com miui calculator](https://user-images.githubusercontent.com/60173587/75621393-ffe8fa00-5b93-11ea-8581-997b909b6b3a.jpg)
![Screenshot_2020-03-01-07-55-25-953_com miui calculator](https://user-images.githubusercontent.com/60173587/75621395-037c8100-5b94-11ea-902d-0b2c7a13a86b.jpg)
![Screenshot_2020-03-01-07-55-34-240_com miui calculator](https://user-images.githubusercontent.com/60173587/75621396-06777180-5b94-11ea-81e7-19e7858affad.jpg)
![Screenshot_2020-03-01-07-56-04-649_com miui calculator](https://user-images.githubusercontent.com/60173587/75621398-0a0af880-5b94-11ea-9c79-2422abbc64e0.jpg)

**Comment by pmspr4100** [comment]
-Fixer
