### ISSUE TITLE
Oublie de traduction

### ISSUE THREAD

**Issue by Fernando-Natali** [pmspr4100/MA-XML-11-FRENCH#27]
Bonjour ;) 

J'ai trouvé un oublie de traduction

- **Version MIUI: 11.0.5 Stable
- **Nom de l'appareil: Redmi Note 8T

**Capture d'écran/Description:**
Paramètres/Paramètres Additionnel

![IMG_20200303_144607](https://user-images.githubusercontent.com/61743385/75782086-a8e35080-5d5e-11ea-9d0f-d75fb85c9827.jpg)

![Screenshot_2020-03-03-14-44-46-476_com android settings](https://user-images.githubusercontent.com/61743385/75782096-ab45aa80-5d5e-11ea-9688-da1cae0b30bb.jpg)

**Comment by pmspr4100** [comment]
-Des proposition de traduction ?

**Comment by jblum66** [comment]
Je soumets une traduction...
