### ISSUE TITLE
2 issues trouver

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#28]
- Version MIUI:   20.2.27 (beta)
- Nom de l'appareil:   Mi CC9

Salut , j'ai trouver quelque issues dans le chemin :

- Paramètres - Retour D'informations - 3 points - Afficher l'historique des commentaires

![Screenshot_2020-03-05-21-17-34-313_com miui bugreport](https://user-images.githubusercontent.com/60173587/76023047-afbdbf00-5f28-11ea-9c1c-73af55868294.jpg)

- Paramètres - Retour D'informations - 3 points - Générer des bugs - Générer le journal

![Screenshot_2020-03-05-21-18-03-476_com miui bugreport](https://user-images.githubusercontent.com/60173587/76023116-cebc5100-5f28-11ea-8f6f-b81bef7faaf4.jpg)

**Comment by pmspr4100** [comment]
-Fixer

**Comment by bigjackwww** [comment]
Merci
