### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#29]
-  Version MIUI: 20.3.5 (beta)
-  Nom de l'appareil:   Mi CC9

Salut , j'ai trouver quelque issues dans le chemin :

-  Paramètres  - Affichage permanent et écran de verrouillage - Fond d"écran carrousel 

![Screenshot_2020-03-06-08-38-54-760_com mfashiongallery emag](https://user-images.githubusercontent.com/60173587/76062760-a2372200-5f86-11ea-9275-15f5beadfe6c.jpg)

-  Paramètres  - Affichage permanent et écran de verrouillage - Fond d'écran carrousel - Paramètre du Diaporama - diaporama et l'écran de verrouillage  (2 cas :  activer-Turn on et désactiver-Turn off) 

![Screenshot_2020-03-06-08-20-25-859_com mfashiongallery emag](https://user-images.githubusercontent.com/60173587/76062894-e1657300-5f86-11ea-8354-7a3f357e8c25.jpg)

-  Paramètres  - Affichage permanent et écran de verrouillage - Fond d"écran carrousel - Gérer 

![Screenshot_2020-03-06-08-37-21-951_com mfashiongallery emag](https://user-images.githubusercontent.com/60173587/76062919-ed513500-5f86-11ea-80e5-0d25ed096d6a.jpg)

- Paramètres  - Paramètre WI-FI - Paramètre additionnels 

![Screenshot_2020-03-06-08-47-57-577_com android settings](https://user-images.githubusercontent.com/60173587/76063189-841df180-5f87-11ea-8965-697651ff5215.jpg)

- Paramètres - Paramètre bluetooth - paramètre additionnels 

![Screenshot_2020-03-06-08-51-19-272_com android settings](https://user-images.githubusercontent.com/60173587/76063372-de1eb700-5f87-11ea-86c8-e8b34fe190aa.jpg)

- Paramètre - connexion et partage - Caster - Aide

![Screenshot_2020-03-06-08-54-26-315_com milink service](https://user-images.githubusercontent.com/60173587/76063616-5f764980-5f88-11ea-8420-6ed00fc37e0d.jpg)

![Screenshot_2020-03-06-08-54-31-575_com milink service](https://user-images.githubusercontent.com/60173587/76063648-70bf5600-5f88-11ea-9a5f-7a3c22225759.jpg)

- Paramètre - connexion et partage - Point d’accès - appareils connecté - limite d'appareils pouvant se connecter 

![Screenshot_2020-03-06-08-58-19-268_com android settings](https://user-images.githubusercontent.com/60173587/76063911-e9bead80-5f88-11ea-82c4-8cb91ee6b3dc.jpg)

- Paramètre - Mot de passe et securité - Alertes d'urgences

![Screenshot_2020-03-06-09-04-23-957_com android cellbroadcastreceiver](https://user-images.githubusercontent.com/60173587/76064244-8f721c80-5f89-11ea-9f20-43e918b4b419.jpg)

- Paramètre - Fonctionnalité spéciales - Mode simplifié 

![Screenshot_2020-03-06-09-07-47-666_com xiaomi misettings](https://user-images.githubusercontent.com/60173587/76064653-630ad000-5f8a-11ea-8aa0-075c5d8f1d7e.jpg)

![Screenshot_2020-03-06-09-09-30-327_com xiaomi misettings](https://user-images.githubusercontent.com/60173587/76064675-6a31de00-5f8a-11ea-9348-05ea6161e7a5.jpg)

- Paramètre - Compte mi - Mi Cloud - Localiser l'appareil 

![Screenshot_2020-03-06-10-52-10-112_com miui cloudservice](https://user-images.githubusercontent.com/60173587/76072999-390cda00-5f99-11ea-8052-bc63c9f6a327.jpg)

**Comment by jblum66** [comment]
Corrigé aujourd'hui, sauf pour le "Unlimited" que je ne trouve pas dans le code source français.

**Comment by bigjackwww** [comment]
D'accord, Merci .

**Comment by pmspr4100** [comment]
Je vais regarder pour le "Unlimited"

**Comment by pmspr4100** [comment]
Normalement c'est OK
