### ISSUE TITLE
MiuiPackageInstaller

### ISSUE THREAD

**Issue by IgorEisberg** [pmspr4100/MA-XML-11-FRENCH#3]
You included Chinese strings in your translation files for MiuiPackageInstaller. If this isn't resolved, we'd have to remove French files for MiuiPackageInstaller for the next release.
Refer to our XML files for the correct English strings and don't include untranslated strings in your translated files at all:
https://github.com/ingbrzy/Xiaomi.eu-MIUIv11-XML-Compare/tree/master/cepheus/MiuiPackageInstaller.apk/res/values

**Comment by pmspr4100** [comment]
Hello
Actually some channels were in Chinese, I had to recover the file when MiuiPackage and arrives on the GitHub.
I just reapplied a fix with the right lines in French.

However lines Chonois are integrated on your side so I do not understand why on MiuiPackage that raises a problem?
