### ISSUE TITLE
issue app behavior

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#31]
-   Version MIUI:  20.3.5 (beta)
-   Nom de l'appareil:  Mi CC9

Salut , j'ai trouver quelque erreur dans le chemin :

-   Paramètres - Gestion des applications - Applications installées 

![Screenshot_2020-03-08-10-26-22-671_com miui securitycenter](https://user-images.githubusercontent.com/60173587/76160220-88cddb80-6128-11ea-92df-3c9f46054551.jpg)

-   Paramètres - Gestion des applications - Applications installées - App behavior

![Screenshot_2020-03-08-10-26-50-902_com miui securitycenter](https://user-images.githubusercontent.com/60173587/76160232-9f743280-6128-11ea-96e1-54370f22fe07.jpg)

-   Paramètres - Gestion des applications - Applications installées - App behavior - 3 points

![Screenshot_2020-03-08-10-26-59-295_com miui securitycenter](https://user-images.githubusercontent.com/60173587/76160243-b74bb680-6128-11ea-948e-6daff663ee69.jpg)

-   Paramètres - Gestion des applications - Applications installées - App behavior - 3 points - Notifications about sensitive actions

![Screenshot_2020-03-08-10-27-09-252_com miui securitycenter](https://user-images.githubusercontent.com/60173587/76160251-c5013c00-6128-11ea-9493-152bfbf2a58f.jpg)

-   Paramètres - Gestion des applications - Applications installées - App behavior - 3 points -
About app behavior records

![Screenshot_2020-03-08-10-27-17-214_com miui securitycenter](https://user-images.githubusercontent.com/60173587/76160254-c894c300-6128-11ea-8c2b-324d872c8617.jpg)

-   Paramètres - Gestion des applications - Applications installées 
Sélectionner n'importe quel application installer par l'utilisateur 

![1](https://user-images.githubusercontent.com/60173587/76160045-e5c89200-6126-11ea-9c11-afdd1b9c2d48.jpg)

-   Paramètres - Gestion des applications - Applications installées - App behavior

![2](https://user-images.githubusercontent.com/60173587/76160063-101a4f80-6127-11ea-8c5e-0689929537ae.jpg)

-   Paramètres - Gestion des applications - Applications installées - App behavior - Paramètre

![3](https://user-images.githubusercontent.com/60173587/76160073-22948900-6127-11ea-9cca-8b0ad06d7636.jpg)

**Comment by pmspr4100** [comment]
-Fixer

**Comment by bigjackwww** [comment]
Merci bcp
