### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#33]
-   Version MIUI:  20.3.12 (Beta)
-   Nom de l'appareil:  Mi CC9

Salut, j'ai trouver quelque erreur de traduction dans le chemin :

- Paramètre - Affichage permanent et écran de verrouillage - Fond d’écran carrousel - salutations du matin

![Screenshot_2020-03-14-04-08-23-297_com mfashiongallery emag](https://user-images.githubusercontent.com/60173587/76673868-b3e18080-65a9-11ea-84a0-40f65c508fa3.jpg)

- Paramètre - Affichage permanent et écran de verrouillage - Fond d’écran carrousel - Favoris ( Notification)

![Screenshot_2020-03-14-04-36-01-374_com mfashiongallery emag](https://user-images.githubusercontent.com/60173587/76674257-9d3d2880-65ad-11ea-9e70-36be73612fbd.jpg)

- Paramètre - Paramètre additionnels - options développeurs

![Screenshot_2020-03-14-04-17-11-882_com android settings](https://user-images.githubusercontent.com/60173587/76673979-f0fa4280-65aa-11ea-918a-1e540512c5c1.jpg)

- Paramètre - bien être numérique

![Screenshot_2020-03-14-04-20-13-884_com xiaomi misettings](https://user-images.githubusercontent.com/60173587/76674021-682fd680-65ab-11ea-826e-1c7ee36fef05.jpg)

![Screenshot_2020-03-14-04-20-19-117_com xiaomi misettings](https://user-images.githubusercontent.com/60173587/76674027-71b93e80-65ab-11ea-85f3-224a5cb700f7.jpg)

- Paramètre - bien être numérique - Afficher les statistiques détaillées  
  
![Screenshot_2020-03-14-04-23-34-349_com xiaomi misettings](https://user-images.githubusercontent.com/60173587/76674081-d96f8980-65ab-11ea-80a3-a90d7ac6c235.jpg)

- Paramètre - Mon appareil - Sauvegarder, restaurer ou réinitialiser 
 
![Screenshot_2020-03-14-04-29-19-995_com android settings](https://user-images.githubusercontent.com/60173587/76674168-a37ed500-65ac-11ea-866e-5d413ccf29ab.jpg)

- Paramètre - Mon appareil - Sauvegarder, restaurer ou réinitialiser - Effacer toutes les données ( rétablir la configuration d'usine) 

![Screenshot_2020-03-14-04-29-53-283_com android settings](https://user-images.githubusercontent.com/60173587/76674188-d1641980-65ac-11ea-886e-f347e81d4978.jpg)

- Paramètre - connexion et partage - Caster - Aide

![Screenshot_2020-03-14-04-42-11-311_com milink service](https://user-images.githubusercontent.com/60173587/76674315-56036780-65ae-11ea-96b3-767191748912.jpg)

- Paramètres - Gestion des applications - Applications installées - Comportement de l'application - 3 points

![Sans titre](https://user-images.githubusercontent.com/60173587/76677104-b0122600-65ca-11ea-8a52-c8cb3f2752fa.jpg)

**Comment by pmspr4100** [comment]
-Fixer

**Comment by bigjackwww** [comment]
Merci beaucoup
