### ISSUE TITLE
Issue Option développeur 

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#34]
-   Version MIUI:  20.3.12 (Beta)
-   Nom de l'appareil:  Mi CC9

Salut, j'ai trouver quelque erreur de traduction dans le chemin :

- Paramètre - Paramètre additionnels - options pour les développeur  - Mode sombre

![Screenshot_2020-03-15-06-43-16-002_com android settings](https://user-images.githubusercontent.com/60173587/76696158-9c2cf980-6688-11ea-8a98-31e8dd6af274.jpg)

- Paramètre - Paramètre additionnels - options pour les développeur  - Bluetooth audio LDAC codec: qualité de lecture 

![Screenshot_2020-03-15-06-47-05-474_com android settings](https://user-images.githubusercontent.com/60173587/76696208-207f7c80-6689-11ea-9ee2-bf03ce402d91.jpg)

- Paramètre - Paramètre additionnels - options pour les développeur  - Simuler des affichages secondaires

![Screenshot_2020-03-15-06-50-57-917_com android settings](https://user-images.githubusercontent.com/60173587/76696242-85d36d80-6689-11ea-8f37-9fbec16825bf.jpg)

- Paramètre - Paramètre additionnels - options pour les développeur  - Moniteur de puissance

![Screenshot_2020-03-15-06-53-22-316_com miui powerkeeper](https://user-images.githubusercontent.com/60173587/76696270-d34fda80-6689-11ea-8279-b36f7b0cf74d.jpg)

- Paramètre - Paramètre additionnels - options pour les développeur  - Couleur des accents

![Screenshot_2020-03-15-06-55-36-355_com android settings](https://user-images.githubusercontent.com/60173587/76696311-36da0800-668a-11ea-8bd0-da02c8c18818.jpg)

- Paramètre - Paramètre additionnels - options pour les développeur  - Forme de l'icone

![Screenshot_2020-03-15-06-55-44-684_com android settings](https://user-images.githubusercontent.com/60173587/76696315-45282400-668a-11ea-8866-780cd6a5e898.jpg)

**Comment by pmspr4100** [comment]
Pourtant les traductions sont bien disponibles.
donc si pour la prochaine version cela ne fonctionne pas je vais devoir séparer certains fichiers pour chaque modèle de smartphones.

**Comment by bigjackwww** [comment]
Ok Merci.
