### ISSUE TITLE
Issue Comportement de L'application

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#36]
-   Version MIUI:   20.3.19 (Beta) 
-   Nom de l'appareil:   Mi CC9

Salut , j'ai trouver quelque erreur dans le chemin :

-  Paramètres - Gestion des applications - Applications installées - Comportement de L'application
Sélectionné  application installé 

![Screenshot_2020-03-20-21-55-45-910_com miui securitycenter](https://user-images.githubusercontent.com/60173587/77206312-ec77e180-6af6-11ea-8cc1-f72a8540df1d.jpg)

-  Paramètres - Gestion des applications - Applications installées - Comportement de L'application
Sélectionné  application installé - Paramètre

![Screenshot_2020-03-20-21-56-05-548_com miui securitycenter](https://user-images.githubusercontent.com/60173587/77206436-411b5c80-6af7-11ea-97a8-5e0cea9c6bf7.jpg)

-  Paramètres - Gestion des applications - Applications installées - Comportement de L'application
Sélectionné  application installé - Permissions 

![Screenshot_2020-03-20-21-56-56-652_com miui securitycenter](https://user-images.githubusercontent.com/60173587/77206477-57c1b380-6af7-11ea-9ad4-7b27ea07b90a.jpg)

**Comment by pmspr4100** [comment]
- Traduit mais l'intégration sera pour la prochaine version.

**Comment by bigjackwww** [comment]
D'accord, Merci beaucoup
