### ISSUE TITLE
Issue GPS autorisation

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#39]
-  Version MIUI: 20.3.19 (Beta)
-  Nom de l'appareil: Mi CC9

Salut, j'ai installé un application qui demande l'autorisation de localisation GPS et j'ai trouvé un erreur de traduction. et aussi manque la fin du mot a propos de toutes les autres autorisations :

![Sans titre](https://user-images.githubusercontent.com/60173587/77506124-50870680-6e65-11ea-866d-26ecd9edae08.jpg)

**Comment by pmspr4100** [comment]
-Fixer
