### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#41]
-   Version MIUI:  20.3.26 (Beta)
-   Nom de l'appareil:  Mi CC9

Salut , j'ai trouver un erreur de traduction dans le chemin :

- Paramètres - Affichage - Mode sombre

![Screenshot_2020-03-28-02-20-55-799_com android settings](https://user-images.githubusercontent.com/60173587/77811597-b2c94c80-709b-11ea-8fbc-aaec76dd3936.jpg)

**Comment by pmspr4100** [comment]
-Aucune erreur de traduction, juste qu'ils ont compilé les ROMs avant la finalisation des traductions.
-Donc pour la prochaine version.
