### ISSUE TITLE
Mi Vidéo 

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#43]
-  Version MIUI: 20.3.26 (Beta)
-  Nom de l'appareil: Mi CC9

Salut , j'ai trouver un erreur de traduction dans l'application Mi Vidéo : (Play video with screen off)

![Sans titre](https://user-images.githubusercontent.com/60173587/77994499-0a78e980-7322-11ea-8393-e663d53dd5c1.jpg)

**Comment by pmspr4100** [comment]
-Corriger.
