### ISSUE TITLE
Radio FM

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-11-FRENCH#45]
-  Version MIUI: 20.3.26 (Beta)
-  Nom de l'appareil: Mi CC9

Salut , j'ai trouver un erreur de traduction dans l'application Radio FM : (notification)

![Screenshot_2020-04-04-13-11-13-229_com miui fm](https://user-images.githubusercontent.com/60173587/78452329-9c665680-7682-11ea-8787-ee87f6d4986c.jpg)

**Comment by pmspr4100** [comment]
-Corriger

**Comment by bigjackwww** [comment]
Merci bcp pour votre travail
