### ISSUE TITLE
Erreurs grammaticales sur le repo lui-même (ça la fout mal...)

### ISSUE THREAD

**Issue by FlorentLM** [pmspr4100/MA-XML-11-FRENCH#46]
* [README.md](https://github.com/pmspr4100/MA-XML-11-FRENCH/blob/master/README.md) : "Applications MIUI (APK) pour **tout** les appareils Xiaomi" --> **tous**

* Le label "**terminer**" dans les issues fermées --> **terminé**

**Comment by pmspr4100** [comment]
Ça la fout mal !
Suffit de cloné le Git, faire les corrections et pour finir un Pull.
Facile de mettre un titre comme le tiens sans corrections.
