### ISSUE TITLE
Translation bug :-)

### ISSUE THREAD

**Issue by nesquix** [pmspr4100/MA-XML-11-FRENCH#5]
![Screenshot_2020-01-05-23-13-27-344_com miui gallery](https://user-images.githubusercontent.com/22064024/71790800-16019080-3011-11ea-94f8-9f9cf727596a.jpg)

- **Version MIUI:** 11.0.5
- **Nom de l'appareil:** Mi note 10

**Capture d'écran/Description:**
App appareil photo : il est écrit 48mpx au lieu de 108mpx

App package Installer : Il y a encore des phrases en chinois, quand la source d'installation et non vérifiée et qu'il demande un scan avant installation, tout est en chinois. Par exemple quand tu installe un apk depuis solid explorer ou edxposed

Dans paramètres, accessibilité, accessibility menu, tout est en anglais cette fois
Et je ne sais pas si tu peux faire quelque chose pour ça mais quand tu active l'advanced power menu, certaines phrases sont trop longues et se chevauchent, genre reboot fasboot et reboot recovery
Il faudrait juste mettre fasboot ou recovery
Voilà!
Merci beaucoup

**Comment by pmspr4100** [comment]
Pour le mode de redémarrage corriger.
Tu tourne sur une ROM Stable donc les corrections de traductions seront pris en compte sur la prochaine ROM Stable.

**Comment by nesquix** [comment]
Merci pour tous.
